image: Visual Studio 2017
version: 1.0.0-{build}
configuration: Release
build_script:
- cmd: >-
    dotnet restore

    dotnet build
artifacts:
  - path: '**\*.nupkg'
    name: NugetPackages

deploy:
  provider: NuGet
  api_key:
    secure: fRlF4yx/WN882TB6FkIPbSDyoViXQWZlRH1MVdUTdSlrLXivTCNFBHJpvwFv+1sF
  skip_symbols: false
  artifact: NugetPackages
  on:
    appveyor_repo_tag: true
